constantinpape/z5

- src/python/test/test_dataset.py
The test currently fails because the returned array always has shape `(1,)` as defined in the [python wrapper](https://github.com/constantinpape/z5/blob/master/src/python/module/z5py/dataset.py#L178) of the `array_to_format` method.
Maybe simply return the resulting bytes instead of taking an `out` parameter so that you don't need to allocate any shape beforehand?
> Add test to check equality of conversion to binary dump and writing to disk

- src/python/module/z5py/file.py
Previously, __enter__ and __exit__ were not defined, meaning that z5py
could not be used as a drop-in replacement for h5py. Now they have
trivial definitions which currently have no value besides having a more
h5pythonic interface.
> File: Add trivial context manager dunder

- src/python/module/z5py/attribute_manager.py
- src/python/test/test_attributes.py
Under zarr v2, .zattrs file is optional. However, in z5py an error
would be thrown if iterating through or doing membership checks of
attributes when that file did not exist.
Now the error is caught and an empty dict returned.
> Handle nonexistent attribute files

- src/python/module/z5py/__init__.py
- src/python/module/z5py/file.py
- src/python/test/test_file.py
These just inherit from and call the constructor of File.
Minor changes:
- fixed bug where zarr files could not be created unless they had the
correct extension, even if `use_zarr_format` was given explicitly
This is a minor convenience, no need to rush a release out once it's merged.
> File: Add direct constructors for Zarr, N5 files

- src/python/module/z5py/attribute_manager.py
- src/python/module/z5py/dataset.py
- src/python/test/test_attributes.py
- src/python/test/test_dataset.py
AttributeManager was missing some behaviour because h5py's inherits from MutableMapping, so I've refactored it to do the same, among some other minor changes.
Datasets could not be created with certain types of dtype spec (e.g. `np.uint8`), so I've made a small change to allow that too.
Query: in the existing implementation, N5 metadata can be addressed through the AttributeManager using `__getitem__`, but zarr metadata cannot. Neither can be written through the AttributeManager (which I agree with), and neither show up when iterating through or doing membership checks - the latter is inconsistent given the `__getitem__` behaviour. I think it makes more sense for N5 metadata to be invisible to the AttributeManager regardless of you how access it, just like it is for zarr. The new …
> AttributeManager refactor and Dataset dtype specs

- .travis.yml
- include/z5/multiarray/broadcast.hxx
- include/z5/multiarray/xtensor_access.hxx
- include/z5/types/types.hxx
- include/z5/util/threadpool.hxx
- src/python/lib/dataset.cxx
- src/python/module/z5py/base.py
- src/python/module/z5py/dataset.py
- src/python/test/test_dataset.py
This PR includes two changes:
* Options for multi-threaded reading and writing of data (default is single-threaded)
* Fix Issue that prevented scalar broadcasting from python (see #50)
The number of threads can be set either when creating a dataset via
`ds = create_dataset(..., n_threads=8)` or at any time via `ds.n_threads = 8`.
Note that the number of threads will not be serialized and thus must be reset to the
desired number each time a dataset is loaded.
> Mthread cpp

- .travis.yml
- src/bench/bench_java/n5_benchmark.py
- src/python/module/z5py/util.py
- src/python/test/test_converter.py
- src/python/test/test_regression.py
- src/python/test/test_util.py
Firstly, use a timedelta-backed `z5py.util.Timer` to measure timings for regression tests and benchmarks, for the sake of precision.
Second change is more subjective, and it's up to you if you want it to go in: use buffers to avoid having to A) depend on `wget` and B) save intermediate files when fetching the test data set. In order to do this, I switched from using `skimage.io` to using `imageio` (which is officially the replacement for `scipy.misc.imread`), because that explicitly handles buffers, where `skimage` doesn't say it does. While doing this, I realised that `imageio` bundles its own volumetric data example, so I have a function for fetching that as an alternative, which may be less brittle. That would require re-timing the benchmarks, though.
> Regression test accuracy

- src/python/module/z5py/util.py
Forgot py2 response objects aren't context managers.
> Fix py2 urllib closing failure

- src/python/module/z5py/__init__.py
For convenience.
It needs to be remembered when making new releases, though. It's easy enough to `sed` for in any release script you may have. Tools like [bumpversion](https://pypi.org/project/bumpversion/) can handle this for you, if you have the version string specified in multiple places (e.g. might be a good idea for it to be in the docs as well).
> Add __version__ and __version_info__ to __init__.py

- CMakeLists.txt
- include/z5/file.hxx
This pull request:
1. added isZarr as an input argument of Metadata object in file creation. It solved the missing piece due to the commit 40856ba.
2. added nlohmann_json support in CMakeLists. nlohmann_json is included in all environment scripts but is not written into the CMakeLists.txt which leads to a missing package in the project.
> fix file creation and add nlohmann_json support in CMakeLists

- CMakeLists.txt
- appveyor.yml
- include/z5/attributes.hxx
- include/z5/dataset_factory.hxx
- include/z5/handle/file_mode.hxx
- include/z5/handle/handle.hxx
- include/z5/io/io_base.hxx
- include/z5/io/io_n5.hxx
- include/z5/io/io_zarr.hxx
- include/z5/metadata.hxx
- include/z5/util/functions.hxx
- src/python/lib/CMakeLists.txt
- src/test/CMakeLists.txt
- src/test/io/test_helper.hxx
- src/test/io/test_io_n5.cxx
- src/test/io/test_io_zarr.cxx
- src/test/multiarray/test_broadcast.cxx
- src/test/multiarray/test_marray.cxx
- src/test/multiarray/test_xtensor.cxx
- src/test/multiarray/test_xtnd.cxx
- src/test/multiarray/test_xtutil.cxx
- src/test/test_attributes.cxx
- src/test/test_dataset.cxx
- src/test/test_factories.cxx
- src/test/test_metadata.cxx
- src/test/test_n5/test_n5.cxx
This turned out to be a bit more complicated due to std::experimental::filesystem in gcc7.
> Make boost::filesystem optional if we have c++17

- CMakeLists.txt
Your original fix (now erased via force-push) was mostly correct -- there was just a typo.
Here's the difference between your old commit and this one:
```diff
-SET(FILESYSTEM_LIBRARIES "libc++experimental")
+SET(FILESYSTEM_LIBRARIES "c++experimental")
```
> mac: Fix linking for libc++experimental

- include/z5/handle.hxx
Hello @constantinpape ,
thank you for this awesome library.
The **z5 library** is currently used during reinforcement learning for a neural network chess variant engine _CrazyAra_ to export data in the [**Zarr**](https://github.com/zarr-developers/zarr-python) data format.
* https://github.com/QueensGambit/CrazyAra/blob/master/engine/src/rl/traindataexporter.h
I needed to add `#include <set>` from the C++ standard library to avoid compilation errors on my system.
* https://github.com/constantinpape/z5/blob/master/include/z5/handle.hxx#L166
Moreover, it could be useful to add a note in the readme install instructions that the [boost library](https://www.boost.org/) is required to use the **z5 library**.
Currently, the boost library is installed form sourceforge.net via our Dockerfile:
* …
> added #include <set>

- include/z5/metadata.hxx
- include/z5/types/types.hxx
- src/python/module/z5py/dataset.py
- src/python/test/test_dataset.py
- Allows for using `NaN`, `Inf` and `-Inf` as fill values. Tested with my R wrappers only for `NaN`, I will test it for `Inf` tomorrow. #148 
- This PR also fixes a small bug (?): The raw compressor was missing from one of the maps between the compressor type and the string value.
- Not sure which `NaN` value to use, currently using `std::numeric_limits<double>::quiet_NaN()`.
- No new unit tests.
- I cannot run the tests on my computer, because my OS is too old, so I simply transferred all the changes between files and did not run the tests.
> add support for NaN fill values

- appveyor.yml
- conda-recipe/meta.yaml
- src/python/module/z5py/file.py
- src/python/test/test_file.py
Added a check if path that is supplied to File is of type `pathlib.Path`.
Also added a test for it and made the conda recipe run the tests.
fixes #160
> Fix error when pathlib.Path is supplied to File

- src/python/module/z5py/dataset.py
- src/python/test/test_asarray.py
This addresses #179 and makes z5py more feature-for-feature compatible with h5py (using this interface may not be suitable for larger datasets, but that is the same as h5py).
> Implement assarray in the z5py dataset class for better numpy interactions

- .github/workflows/build.yml
For some reason `msvc-dev-cmd` does not really like the environment after `setup-miniconda` does its job. As a workaround, configure MSVC environment first, then install miniconda. This lets them coexist for now.
Once the issue with `msvc-dev-cmd` is resolved (https://github.com/ilammy/msvc-dev-cmd/issues/34), this step can be moved back to its original location.
Supersedes: #181
> Work around MSVC build issues

- README.md
- include/z5/compression/xz_compressor.hxx
- include/z5/compression/zlib_compressor.hxx
- include/z5/filesystem/dataset.hxx
- include/z5/filesystem/handle.hxx
- include/z5/handle.hxx
- include/z5/multiarray/xtensor_util.hxx
- include/z5/s3/dataset.hxx
- include/z5/s3/handle.hxx
- include/z5/types/types.hxx
- include/z5/util/format_data.hxx
- include/z5/util/util.hxx
- src/python/lib/handles.cxx
- src/python/module/z5py/converter.py
- src/python/module/z5py/file.py
- src/python/module/z5py/group.py
- src/python/module/z5py/util.py
- src/python/test/test_zarr.py
- src/test/test_dataset.cxx
- src/test/test_n5/n5_java/src/test/java/zarr_pp/n5/AppTest.java
Mostly in code comments but also in the documentation.
> Fix typos found by codespell

- CMakeLists.txt
I believe if the Python interface is not needed, than we can drop xtensor-python requirement.
> Remove xtensor-python dependency if no Python interface needed

- src/test/test_dataset.cxx
Although both are legal in C++, the latter is prevalent and ISO C99 reads:
> 6.11.5 Storage-class specifiers
> 
> 1 The placement of a storage-class specifier other than at the beginning of the declaration specifiers in a declaration is an obsolescent feature.
> const static → static const

- .github/workflows/environment.yaml
- CMakeLists.txt
- include/z5/common.hxx
- include/z5/factory.hxx
- include/z5/filesystem/attributes.hxx
- include/z5/filesystem/dataset.hxx
- include/z5/filesystem/handle.hxx
- include/z5/filesystem/metadata.hxx
- include/z5/util/threadpool.hxx
- src/python/lib/variant_cast.hxx
- src/test/test_metadata.cxx
- Use C++ 17 standard
- Replace `boost::filesystem` with `std::filesystem`
- Replace `boost::variant` with `std::variant`
- Remove `boost::counting_iterator` 
- Update GitHub Action build dependency
- Remove `boost` from `CMakeLists.txt`
This PR is a follow-up of #223. Once this gets merged, we can update the doc and conda-recipe related files with a separate PR.
> Drop boost requirement

- include/z5/util/threadpool.hxx
The package can now be compiled with c++20. Compling with standards before 20 is not affected.
> fix problem when compiling with c++20

- .github/workflows/build.yml
- .github/workflows/environment.yaml
- src/python/CMakeLists.txt
Since `distutils` module is deprecated in Python 3.12, using `sysconfig` module to get Python site-package location
> Replace distutils module

- include/z5/filesystem/factory.hxx
- include/z5/metadata.hxx
- include/z5/types/types.hxx
- src/python/lib/dataset.cxx
- src/test/test_dataset.cxx
NPY and Zarr support complex floating point tensors with the `<c` dtype prefix, but are not yet supported by z5. This changeset adds support for 3 fixed sized complex dtypes made available and tested using the C++ standard library `std::complex<T>`.
External to this PR I've tested loading complex tensors from Zarr but not N5, if there's evidence N5 does support complex numbers I'd be open to exploring support for N5 too.
> Add Complex Number Support
